# generated 2022-12-12 22:03:12

#Generic functions
_path2logs='/opt/share/yamon/logs/'
_path2data='/opt/share/yamon/data/'
dailyLogFile='/opt/share/yamon/logs/2022-12-12.html'
_currentInterval='2022-12'
_path2CurrentMonth='/opt/share/yamon/data/2022/12/'
_intervalDataFile='/opt/share/yamon/data/2022/12/2022-12-mac_usage.js'
_uptime='3095.56'
lastCheckinHour='57'
_path2bu='/opt/share/yamon/daily-bu/'
_usersFile='/opt/share/yamon/data/users.js'
tmpUsersFile='/tmp/yamon/users.js'
_lastSeenFile='/opt/share/yamon/data/lastseen.js'
tmpLastSeen='/tmp/yamon/lastseen.js'
rawtraffic_day='/opt/share/yamon/data/2022/12/raw-traffic-2022-12-12.txt'
rawtraffic_hr='/tmp/yamon/raw-traffic-2022-12-12-22.txt'
hourlyDataFile='/tmp/yamon/hourly_2022-12-12.js'
macIPFile='/tmp/yamon/mac-ip.txt'

#ip v4 & v6 paths & functions
YAMON_IPTABLES='YAMONv40'
_generic_ipv4='0.0.0.0/0'
_generic_ipv6='::/0'
_IPCmd='ip neigh show'
send2FTP='Send2FTP_0'

#livedata.sh
_conntrack='/proc/net/nf_conntrack'
_conntrack_awk='BEGIN { printf "curr_connections=[" } { gsub(/(con|src|dst|sport|dport|bytes)=/, ""); if($3 == "tcp"){ printf "{con:\"%s\",src:\"%s\",dst:\"%s\",sport:%s,dport:%s,bytes:%s},",$3,$7,$8,$9,$10,$12; } else if($3 == "udp"){ printf "{con:\"%s\",src:\"%s\",dst:\"%s\",sport:%s,dport:%s,bytes:%s},",$3,$6,$7,$8,$9,$11; } else { printf "{con:\"%s\",src:\"%s\",dst:\"%s\",sport:\"%s\",dport:\"%s\",bytes:\"%s\"},",$3,$6,$7,$8,$9,$11;} } END { printf "];" }'
_liveFilePath='/tmp/www/js/live_data4.js'
doCurrConnections='CurrentConnections_1'
doArchiveLiveUpdates='ArchiveLiveUpdates_0'
hourlyDataTemplate='hourlyData4({\"id\":\"%s\",\"hour\":\"%s\",\"down\":\"%s\",\"up\":\"%s\"})'
currentlyUnlimited='0'

#Firmware specfic & dependent entries:
nameFromStaticLeases='StaticLeases_DDWRT'
deviceIPField='3'
deviceNameField='2'
_dnsmasq_conf='/tmp/dnsmasq.conf'
_dnsmasq_leases='/tmp/dnsmasq.leases'
_wwwPath='/tmp/www/'
_wwwURL='/user'
_iptablesWait=''
_lan_iface='br-0'
_interfaces='br0,vlan2'
ip6tablesFn='NoIP6'
ip6Enabled=''
nameFromDNSMasqConf='DNSMasqConf'
nameFromDNSMasqLease='NullFunction'
_max_digits='10'
_setRenice='SetRenice'
interface_br0='0,0'
interface_vlan2='20610,24216'
